Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/heatsource900/BigRedButton.py", line 225, in RunHS
    HSP = ModelControl(inputdir, control_file)
  File "/usr/local/lib/python2.7/dist-packages/heatsource900/BigRedButton.py", line 68, in __init__
    self.HS = CSVInterface(inputdir, control_file, self.ErrLog, run_type)
  File "/usr/local/lib/python2.7/dist-packages/heatsource900/CSV/CSVInterface.py", line 66, in __init__
    self.GetContinuousData()
  File "/usr/local/lib/python2.7/dist-packages/heatsource900/CSV/CSVInterface.py", line 578, in GetContinuousData
    else: raise Exception("Cloudiness (value of '%s' in Continuous Data) must be greater than zero and less than one." % `cloud`) # TODO RM fix this so it gives the km in exception - actualy do for all
Exception: Cloudiness (value of '1.9012035' in Continuous Data) must be greater than zero and less than one.
